# Generated by Django 2.2.24 on 2021-09-01 00:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=120, null=True)),
                ('type', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VISIBLE', 'Visible'), ('PRINT', 'Print')], default='READ', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Object')),
                ('operation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Operation')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=250)),
                ('role_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('role_id_ssd', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='role_id_ssd')),
                ('role_id_dsd', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='role_id_dsd')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.User')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Permission_role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('permission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Permission')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Role')),
            ],
        ),
    ]
